// tokens/build.mjs
//
// Automated design-token generator for Orbital Archive No. 01 (Lunar Signal Modernism).
//
// Source of truth: tokens/tokens.json (W3C DTCG format — $value / $type, with
// alias references like "{color.palette.teal}"). This script uses Style Dictionary
// purely as the DTCG parser + alias resolver + file writer; every output byte is
// shaped by the custom formats below so the emitted files exactly match the
// design system's platform contracts.
//
// Run with: npm run build:tokens  (node tokens/build.mjs)
//
// Produces, under tokens/dist/:
//   tokens.css          CSS custom properties (:root)   -- consumed at runtime by the guide
//   tokens.ts           per-category TS exports + flatTokens map
//   tokens.native.ts    identical to tokens.ts (native entry point)
//   tailwind-theme.ts   flattened Tailwind theme object
//   react-native.ts     nested RN token object (curated subset)
//   Tokens.swift        SwiftUI Color / CGFloat constants
//   LSMTokens.kt        Jetpack Compose Color / dp constants
//   tokens.dart         Flutter Color / double constants
//   android/colors.xml  Android color resources (ARGB)
//   android/dimens.xml  Android dimension resources (dp)

import StyleDictionary from "style-dictionary";

const HEADER_SLASH = "// AUTO-GENERATED by tokens/build.mjs. Do not edit.";
const HEADER_CSS = "/* AUTO-GENERATED by tokens/build.mjs. Do not edit. */";
const HEADER_XML = "<!-- AUTO-GENERATED by tokens/build.mjs. -->";
const PREFIX = "lsm";

// ---------------------------------------------------------------------------
// Name helpers — a token path (array of raw JSON segments) becomes a name in
// each platform's convention. camelCase segments split into words; underscores
// are word boundaries ("0_5" -> ["0","5"]); digits stay attached to letters
// ("display2" and "2xl" stay whole).
// ---------------------------------------------------------------------------
const words = (seg) =>
  String(seg)
    .replace(/_/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean);

const cap = (w) => w.charAt(0).toUpperCase() + w.slice(1);
const allWords = (path) => path.flatMap(words);

const kebabName = (path) => [PREFIX, ...allWords(path)].join("-"); // lsm-color-palette-orbit
const snakeName = (path) => [PREFIX, ...allWords(path)].join("_"); // lsm_color_palette_orbit
const pascalName = (path) => allWords(path).map(cap).join(""); //     ColorPaletteOrbit
const camelName = (path) => {
  const p = pascalName(path);
  return p.charAt(0).toLowerCase() + p.slice(1); //                   colorPaletteOrbit
};
// Object key for nested JS/TS structures: camelCase of a single segment.
// ("surfaceElevated" -> "surfaceElevated", "0_5" -> "05", "2xl" -> "2xl")
const camelKey = (seg) =>
  words(seg)
    .map((w, i) => (i === 0 ? w : cap(w)))
    .join("");

// ---------------------------------------------------------------------------
// Value helpers
// ---------------------------------------------------------------------------
const isDeprecated = (t) => (t.original?.$description ?? "").startsWith("Deprecated");
const refPath = (t) => t.original.$value.replace(/[{}]/g, "").split("."); // {a.b.c} -> [a,b,c]

// Numeric string from a dimension value: strip px/em, keep it minimal ("96px"
// -> "96", "-0.02em" -> "-0.02", "0px" -> "0").
const dimNumber = (v) => String(v).replace(/(px|em)$/, "");
// Minimal number rendering for unitless numeric tokens (0.92, 400, 0, 12).
const rawNumber = (v) => String(v);

// #RRGGBB -> { r, g, b } as 0-255 ints
const hexParts = (hex) => {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16)
  };
};
const hexUpper = (hex) => hex.replace("#", "").toUpperCase(); // 11181E
const rgbFloat = (n) => (n / 255).toFixed(4); //                 0.0667

// ---------------------------------------------------------------------------
// Nested-object builder — used by the TS / tailwind / react-native formats.
// Places each token at camelCase(path[start..]) inside a plain object; leaf =
// value(token). Real JS objects reproduce the source's key ordering, including
// the JS integer-key reordering (space "0_5" sorts after "32").
// ---------------------------------------------------------------------------
const nest = (tokens, start, value) => {
  const root = {};
  for (const t of tokens) {
    const segs = t.path.slice(start);
    let node = root;
    for (let i = 0; i < segs.length - 1; i++) {
      const k = camelKey(segs[i]);
      node[k] = node[k] ?? {};
      node = node[k];
    }
    node[camelKey(segs.at(-1))] = value(t);
  }
  return root;
};

// Inject a JSDoc @deprecated comment above the deprecated token's key line in a
// JSON.stringify'd block, matching the key's own indentation.
const injectDeprecatedJsDoc = (json, token) => {
  const key = camelKey(token.path.at(-1)); // relay
  const canon = camelKey(refPath(token).at(-1)); // teal
  const re = new RegExp(`^(\\s*)"${key}":`, "m");
  return json.replace(
    re,
    (m, indent) => `${indent}/** @deprecated Use ${canon}; ${key} will be removed in v2. */\n${m}`
  );
};

// TS/tailwind/RN leaf value = the resolved DTCG value as-is (hex string,
// dimension string, unitless number, or fontFamily array).
const tsValue = (t) => t.$value;

// Render `export const <name> = <obj> as const`, injecting the deprecation
// JSDoc for any deprecated token contained in `tokens`.
const tsExport = (name, obj, tokens) => {
  let json = JSON.stringify(obj, null, 2);
  for (const t of tokens) if (isDeprecated(t)) json = injectDeprecatedJsDoc(json, t);
  return `export const ${name} = ${json} as const`;
};

// ---------------------------------------------------------------------------
// Custom formats
// ---------------------------------------------------------------------------

// 1. tokens.css — every token as a CSS custom property.
StyleDictionary.registerFormat({
  name: "lsm/css",
  format: ({ dictionary }) => {
    const cssValue = (t) =>
      t.$type === "fontFamily" ? t.$value.map((f) => `'${f}'`).join(", ") : String(t.$value);
    const lines = [HEADER_CSS, ":root {"];
    for (const t of dictionary.allTokens) {
      if (isDeprecated(t)) {
        const canonVar = `--${kebabName(refPath(t))}`;
        lines.push(`  /* Deprecated compatibility alias; use ${canonVar}. Remove in v2. */`);
      }
      lines.push(`  --${kebabName(t.path)}: ${cssValue(t)};`);
    }
    lines.push("}");
    return lines.join("\n") + "\n";
  }
});

// 2. tokens.ts (and tokens.native.ts) — per-category nested exports, an
//    aggregate `tokens`, and a `flatTokens` map keyed by raw dotted path.
StyleDictionary.registerFormat({
  name: "lsm/ts",
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens;
    const categories = [...new Set(tokens.map((t) => t.path[0]))];
    // Per-category exports are separated by blank lines...
    const exports = categories.map((cat) => {
      const catTokens = tokens.filter((t) => t.path[0] === cat);
      return tsExport(cat, nest(catTokens, 1, tsValue), catTokens);
    });
    // flatTokens: raw dotted path keys (all contain dots -> insertion order kept).
    const flat = {};
    for (const t of tokens) flat[t.path.join(".")] = tsValue(t);
    // ...but the trailing aggregate / TokenPath / flatTokens trio is contiguous,
    // and the header sits directly above the first export (no blank line).
    return (
      HEADER_SLASH +
      "\n" +
      exports.join("\n\n") +
      "\n\n" +
      `export const tokens = { ${categories.join(", ")} } as const` +
      "\n" +
      "export type TokenPath = keyof typeof flatTokens" +
      "\n" +
      `export const flatTokens = ${JSON.stringify(flat, null, 2)} as const` +
      "\n"
    );
  }
});

// 3. tailwind-theme.ts — a Tailwind theme object with a flattened color map
//    (palette + semantic leaf names) and remapped scale keys.
StyleDictionary.registerFormat({
  name: "lsm/tailwind",
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens;
    const pick = (pred) => tokens.filter(pred);
    const cat = (name) => pick((t) => t.path[0] === name);

    // colors: palette then semantic, keyed by leaf name.
    const colorTokens = pick(
      (t) => t.path[0] === "color" && (t.path[1] === "palette" || t.path[1] === "semantic")
    );
    const colors = {};
    for (const t of colorTokens) colors[camelKey(t.path.at(-1))] = t.$value;

    const theme = {
      colors,
      spacing: nest(cat("space"), 1, tsValue),
      borderRadius: nest(cat("radius"), 1, tsValue),
      fontFamily: nest(cat("font"), 1, tsValue),
      fontSize: nest(cat("fontSize"), 1, tsValue),
      lineHeight: nest(cat("lineHeight"), 1, tsValue),
      fontWeight: nest(cat("fontWeight"), 1, tsValue),
      letterSpacing: nest(cat("letterSpacing"), 1, tsValue),
      opacity: nest(cat("opacity"), 1, tsValue),
      zIndex: nest(cat("zIndex"), 1, tsValue),
      screens: nest(cat("breakpoint"), 1, tsValue),
      boxShadow: nest(cat("shadow"), 1, tsValue)
    };
    let json = JSON.stringify(theme, null, 2);
    for (const t of colorTokens) if (isDeprecated(t)) json = injectDeprecatedJsDoc(json, t);
    return `${HEADER_SLASH}\nexport const lunarSignalTheme = ${json} as const\n`;
  }
});

// 4. react-native.ts — nested RN token object (curated subset of categories).
StyleDictionary.registerFormat({
  name: "lsm/react-native",
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens;
    const cat = (name) => tokens.filter((t) => t.path[0] === name);
    // color: palette + semantic only, keeping the color.<group> nesting.
    const colorTokens = tokens.filter(
      (t) => t.path[0] === "color" && (t.path[1] === "palette" || t.path[1] === "semantic")
    );
    const obj = {
      color: nest(colorTokens, 1, tsValue),
      space: nest(cat("space"), 1, tsValue),
      radius: nest(cat("radius"), 1, tsValue),
      size: nest(cat("size"), 1, tsValue),
      border: nest(cat("border"), 1, tsValue),
      font: nest(cat("font"), 1, tsValue),
      fontSize: nest(cat("fontSize"), 1, tsValue),
      fontWeight: nest(cat("fontWeight"), 1, tsValue),
      lineHeight: nest(cat("lineHeight"), 1, tsValue),
      letterSpacing: nest(cat("letterSpacing"), 1, tsValue),
      opacity: nest(cat("opacity"), 1, tsValue)
    };
    let json = JSON.stringify(obj, null, 2);
    for (const t of colorTokens) if (isDeprecated(t)) json = injectDeprecatedJsDoc(json, t);
    return `${HEADER_SLASH}\nexport const LSMNativeTokens = ${json} as const\n`;
  }
});

// Shared partition for Swift/Kotlin/Dart: colors + fontFamily + dimensions in
// source order (pass 1), then unitless numbers in source order (pass 2). Shadow,
// duration and cubicBezier tokens have no native scalar form and are skipped.
const nativePartition = (tokens) => ({
  primary: tokens.filter((t) => ["color", "fontFamily", "dimension"].includes(t.$type)),
  numbers: tokens.filter((t) => t.$type === "number")
});

// 5. Tokens.swift — SwiftUI constants.
StyleDictionary.registerFormat({
  name: "lsm/swift",
  format: ({ dictionary }) => {
    const { primary, numbers } = nativePartition(dictionary.allTokens);
    const lines = [HEADER_SLASH, "import SwiftUI", "", "public enum LSMTokens {"];
    for (const t of primary) {
      const name = pascalName(t.path);
      if (t.$type === "color") {
        if (isDeprecated(t)) {
          lines.push(
            `    @available(*, deprecated, message: "Use ${pascalName(refPath(t))}; ${name} will be removed in v2.")`
          );
          lines.push(`    public static let ${name} = ${pascalName(refPath(t))}`);
        } else {
          const { r, g, b } = hexParts(t.$value);
          lines.push(
            `    public static let ${name} = Color(red: ${rgbFloat(r)}, green: ${rgbFloat(g)}, blue: ${rgbFloat(b)})`
          );
        }
      } else if (t.$type === "fontFamily") {
        lines.push(`    public static let ${name} = "${t.$value[0]}"`);
      } else {
        lines.push(`    public static let ${name}: CGFloat = ${dimNumber(t.$value)}`);
      }
    }
    for (const t of numbers)
      lines.push(`    public static let ${pascalName(t.path)}: CGFloat = ${rawNumber(t.$value)}`);
    lines.push("}");
    return lines.join("\n") + "\n";
  }
});

// 6. LSMTokens.kt — Jetpack Compose constants.
StyleDictionary.registerFormat({
  name: "lsm/kotlin",
  format: ({ dictionary }) => {
    const { primary, numbers } = nativePartition(dictionary.allTokens);
    const lines = [
      HEADER_SLASH,
      "package design.lunarsignal.tokens",
      "",
      "import androidx.compose.ui.graphics.Color",
      "import androidx.compose.ui.unit.dp",
      "",
      "object LSMTokens {"
    ];
    for (const t of primary) {
      const name = pascalName(t.path);
      if (t.$type === "color") {
        if (isDeprecated(t)) {
          lines.push(
            `    @Deprecated("Use ${pascalName(refPath(t))}; ${name} will be removed in v2.", ReplaceWith("${pascalName(refPath(t))}"))`
          );
          lines.push(`    val ${name} = ${pascalName(refPath(t))}`);
        } else {
          lines.push(`    val ${name} = Color(0xFF${hexUpper(t.$value)})`);
        }
      } else if (t.$type === "fontFamily") {
        lines.push(`    const val ${name} = "${t.$value[0]}"`);
      } else {
        lines.push(`    val ${name} = ${dimNumber(t.$value)}.dp`);
      }
    }
    for (const t of numbers)
      lines.push(`    const val ${pascalName(t.path)} = ${rawNumber(t.$value)}f`);
    lines.push("}");
    return lines.join("\n") + "\n";
  }
});

// 7. tokens.dart — Flutter constants.
StyleDictionary.registerFormat({
  name: "lsm/dart",
  format: ({ dictionary }) => {
    const { primary, numbers } = nativePartition(dictionary.allTokens);
    const lines = [
      HEADER_SLASH,
      "import 'package:flutter/material.dart';",
      "",
      "abstract final class LSMTokens {"
    ];
    for (const t of primary) {
      const name = camelName(t.path);
      if (t.$type === "color") {
        if (isDeprecated(t)) {
          lines.push(
            `  @Deprecated('Use ${camelName(refPath(t))}; ${name} will be removed in v2.')`
          );
          lines.push(`  static const ${name} = ${camelName(refPath(t))};`);
        } else {
          lines.push(`  static const ${name} = Color(0xFF${hexUpper(t.$value)});`);
        }
      } else if (t.$type === "fontFamily") {
        lines.push(`  static const String ${name} = "${t.$value[0]}";`);
      } else {
        lines.push(`  static const double ${name} = ${dimNumber(t.$value)};`);
      }
    }
    for (const t of numbers)
      lines.push(`  static const double ${camelName(t.path)} = ${rawNumber(t.$value)};`);
    lines.push("}");
    return lines.join("\n") + "\n";
  }
});

// 8. android/colors.xml — color resources (ARGB, opaque).
StyleDictionary.registerFormat({
  name: "lsm/android-colors",
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter((t) => t.$type === "color");
    const lines = ['<?xml version="1.0" encoding="utf-8"?>', HEADER_XML, "<resources>"];
    for (const t of colors) {
      const name = snakeName(t.path);
      if (isDeprecated(t)) {
        const canon = snakeName(refPath(t));
        lines.push(`  <!-- Deprecated compatibility alias; use ${canon}. Remove in v2. -->`);
        lines.push(`  <color name="${name}">@color/${canon}</color>`);
      } else {
        lines.push(`  <color name="${name}">#FF${hexUpper(t.$value)}</color>`);
      }
    }
    lines.push("</resources>");
    return lines.join("\n") + "\n";
  }
});

// 9. android/dimens.xml — dimension resources (dp). px-based dimensions only;
//    em-based tokens (letterSpacing) have no dp equivalent and are omitted.
StyleDictionary.registerFormat({
  name: "lsm/android-dimens",
  format: ({ dictionary }) => {
    const dims = dictionary.allTokens.filter(
      (t) => t.$type === "dimension" && String(t.$value).endsWith("px")
    );
    const lines = ['<?xml version="1.0" encoding="utf-8"?>', HEADER_XML, "<resources>"];
    for (const t of dims)
      lines.push(`  <dimen name="${snakeName(t.path)}">${dimNumber(t.$value)}dp</dimen>`);
    lines.push("</resources>");
    return lines.join("\n") + "\n";
  }
});

// ---------------------------------------------------------------------------
// A path-based name transform keeps token names unique (silences Style
// Dictionary's collision warning); the formats above compute their own names.
// ---------------------------------------------------------------------------
StyleDictionary.registerTransform({
  name: "name/lsm-path",
  type: "name",
  transform: (token) => token.path.join(".")
});

const sd = new StyleDictionary({
  source: ["tokens/tokens.json"],
  usesDtcg: true, // parse DTCG $value / $type and resolve {alias} references
  log: { verbosity: "silent", warnings: "disabled" },
  platforms: {
    lsm: {
      transforms: ["name/lsm-path"],
      buildPath: "tokens/dist/",
      files: [
        { destination: "tokens.css", format: "lsm/css" },
        { destination: "tokens.ts", format: "lsm/ts" },
        { destination: "tokens.native.ts", format: "lsm/ts" },
        { destination: "tailwind-theme.ts", format: "lsm/tailwind" },
        { destination: "react-native.ts", format: "lsm/react-native" },
        { destination: "Tokens.swift", format: "lsm/swift" },
        { destination: "LSMTokens.kt", format: "lsm/kotlin" },
        { destination: "tokens.dart", format: "lsm/dart" },
        { destination: "android/colors.xml", format: "lsm/android-colors" },
        { destination: "android/dimens.xml", format: "lsm/android-dimens" }
      ]
    }
  }
});

await sd.buildAllPlatforms();
